////
 README.adoc
-------------------------------------------------------------------------------
   Copyright 2016 Kevin Morey <kevin@redhat.com>

   Licensed under the Apache License, Version 2.0 (the "License");
   you may not use this file except in compliance with the License.
   You may obtain a copy of the License at

       http://www.apache.org/licenses/LICENSE-2.0

   Unless required by applicable law or agreed to in writing, software
   distributed under the License is distributed on an "AS IS" BASIS,
   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
   See the License for the specific language governing permissions and
   limitations under the License.
-------------------------------------------------------------------------------
////

= CloudForms Chef

The purpose of this project is to provide a starting point for integrating Red Hat (R) https://www.redhat.com/en/technologies/cloud-computing/cloudforms[Red Hat CloudForms] and Chef.

== Table of Contents

* <<Overview>>
* <<Install rhconsulting Scripts>>
* <<Download Repo>>
* <<Import the Automate Domain>>
* <<Import the Service Dialogs>>
* <<Import the Custom Buttons>>
* <<Import the Widgets>>
* <<Install Chef Development Kit>>
* link:documentation/userguide.adoc[User Guide]
* link:documentation/troubleshooting.adoc[Troubleshooting Guide]
* <<Contribute>>

=== Overview
COMING SOON!

=== Install rhconsulting Scripts

Follow these steps to install the miqimport/miqexport utilities:

While in `/root` directory, download the rhconsulting repository

 curl -sL  https://github.com/rhtconsulting/cfme-rhconsulting-scripts/tarball/master | tar xvz

Change to the newly created `/root/rhtconsulting-cfme-rhconsulting-scripts` directory, install the rake scripts and utilities:

 make install

The `/usr/bin/miqimport` and `/usr/bin/miqexport` utilities are now available to assist you when importing and exporting from CloudForms.

<<top>>

=== Download Repo

 cd /root
 curl -sL  https://github.com/ramrexx/CloudForms_Chef/tarball/master | tar xvz

<<top>>

=== Import the Automate Domain

 /usr/bin/miqimport domain CloudForms_Chef /root/ramrexx-CloudForms_Chef/automate/

<<top>>

=== Import the Service Dialogs

 /usr/bin/miqimport service_dialogs /root/ramrexx-CloudForms_Chef/service_dialogs/

<<top>>

=== Import the Custom Buttons

 /usr/bin/miqimport buttons /root/ramrexx-CloudForms_Chef/buttons/

<<top>>

=== Import the Widgets

 /usr/bin/miqimport widgets /root/ramrexx-CloudForms_Chef/widgets/

<<top>>

=== Install Chef Development Kit

* Navigate to https://downloads.chef.io/chef-dk/redhat/.
* Choose your version *I usually use the latest*.
* Copy the link to *Red Hat Enterprise Linux 7*.
* SSH into your CloudForms/ManageIQ server.
* Install the Chef Development Kit (as shown below).

 rpm -Uvh https://packages.chef.io/stable/el/7/chefdk-0.19.6-1.el7.x86_64.rpm

* Create the .chef directory.

 mkdir /root/.chef

* Copy the Chef client_key (i.e. root.pem|validator.pem) file to the /root/.chef directory.

* create /root/.chef/knife.rb file.

NOTE: knife.rb must be correctly configured. More info: https://docs.chef.io/config_rb_knife.html. Below is a sample from a working knife.rb file with bare minimum settings.

 cat << EOF > /root/.chef/knife.rb
  current_dir = File.dirname(__FILE__)
  log_level                 :info
  log_location              STDOUT
  node_name                 "admin"
  client_key                "#{current_dir}/chef_key.pem"
  chef_server_url           "https://mychefserver.example.com/organizations/my-org"
  ssl_verify_mode           :verify_none
 EOF

* Test knife to see if you can pull back a list of nodes

 # knife node list -F json
 [
  "vm001"
  "vm002"
  "my-org-validator"
 ]

* Test knife to ensure you can pull back a list of recipes

 # knife recipe list -F json
 [
  "apache2",
  "apache2::mod_access_compat",
  "apache2::mod_actions",
  "apache2::mod_alias"
 ]

* If the knife command(s) above execute without error you are all set!

== Contribute

Have an idea and want to help? Fork the repo and link:https://github.com/ramrexx/CloudForms_Chef/pulls[Submit a pull request]

<<top>>
